### ISSUE TITLE
What names should be stored when children inherit polymorphic relations?

### ISSUE THREAD

**Issue by dallincoons** [tightenco/parental#10]
To provide some context, say there's a Vehicle model with a polymorphic relation to Engine which has an...enginable_type column, for lack of a good name. If Vehicle is extended by Car or Plane, right now the engineable_type will contain the Car and Plane names by default if an engine is associated to one of them instead of Vehicle.

My question is, would it make sense to override this behavior and have the children use the parent model's morph name? My main thinking is that if you're dropping this into an existing application, storing the morph name of the child model subtly changes the behavior of the system and seems like it could be an unintended side effect. What I have in mind is something as simple as this:

```
public function getMorphClass()
{
    return array_search($this->getParentClass(), Relation::morphMap());
}
```

**Comment by calebporzio** [comment]
Is this related to this package? Parental doesn't deal with polymorphic relationships.

**Comment by dallincoons** [comment]
Parental doesn't deal with polymorphic relations, but my question is whether the default Laravel implementation makes sense when using the Parental package or if it should be overridden. Personally, I think the latter makes the most sense.

**Comment by calebporzio** [comment]
Hmm, maybe provide a more clear use case when this behavior would feel weird or cause problems. I see what you're saying, but not sure what to do. Let's table this until someone actually has an issue.
