### ISSUE TITLE
Help with relationships

### ISSUE THREAD

**Issue by roarkmccolgan** [tightenco/parental#21]
Hi Guys.

I'm using parental in my app using Nova and my Users model is my parent, I have a child model (Admins) and a whole bunch of relations on that model.

I am getting errors when viewing my child model and it's relations 
`"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'documents.user_id' in 'where clause' (SQL: select * from `documents` where `documents`.`user_id` = 4 and `documents`.`user_id` is not null)"`

This looks like the issue you mentioned on the blog post about relationships but i thought this package solved these issues by using the use HasParentModel trait?

So, my questions are:
- Do I have to keep all relationships on my parent (Users) model instead of child model?
- Or must I specify the foreign key in the relationship
- Or is this a Nova issue that I need to work around

Thanks for the package and great work

**Comment by calebporzio** [comment]
Take a look at this issue: #20 - is your problem related?
