### ISSUE TITLE
Enforcing Parent Class Contracts

### ISSUE THREAD

**Issue by CPedersen3245** [tightenco/parental#22]
Hey guys,

Not sure if I'm missing something here, but I'd like to be able to enforce this following behaviour in some way:
```php
abstract class Vehicle extends Model
{
    use ReturnsChildModels;

    public abstract function start();
}
```

```php
class Car extends Vehicle
{
    use HasParentModel;

    // HAS to implement parent start() method, won't run otherwise
}
```
If the parent model is abstract, when I call something like `Vehicle::all()`, an exception is thrown saying Vehicle can't be instantiated (which I guess, is kind of expected).

I could make the parent implement an interface, but if I can't make the parent abstract the parent will have to implement the method, which will not enforce the contract for its children.

**Comment by calebporzio** [comment]
I see. That's an interesting point. Right now, I can't think of any solution that wouldn't be horribly janky. If `start()` will definitely get called on every child type, then you could let the system fail, or add a `start()` method to Vehicle and throw an exception in it.

**Comment by calebporzio** [comment]
Closing this for now - open to ideas, but not urgently pursuing this feature.
