### ISSUE TITLE
Observing parent doesn't observe children

### ISSUE THREAD

**Issue by wfeller** [tightenco/parental#23]
Hi,

Looks like when you add an observer to a parent class, the children classes don't benefit from the observer.

It can be solved by adding the following to ReturnsChildModels on the parent class:
```
    public static function observe($classes)
    {
        parent::observe($classes);
        // register the observer on the children only if we're observing the parent
        if (static::class === self::class) { 
            foreach ((new self)->childTypeAliases as $child) {
                $child::observe($classes);
            }
        }
    }
```

This way, adding an observer to the parent will add it to all the children, and adding an observer to a child will only add it to the child.

**Comment by dallincoons** [comment]
I think PRs are welcome ;)
