### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by leeovery** [tightenco/parental#27]
Hey

Thanks for putting this together. Love it.

Can you tag the new release? Getting the old traits pull through with 0.5

Thanks
Lee

**Comment by MitchellMcKenna** [comment]
@leeovery Until then I aliased the latest commit as version 0.5.1, eg.
```
    "require": {
        "tightenco/parental": "dev-master#4eafd3d as 0.5.1",
```

**Comment by calebporzio** [comment]
Just release v0.6 - sorry for the wait!
