### ISSUE TITLE
Date fields are missing in returned object and cannot log in

### ISSUE THREAD

**Issue by ziming** [tightenco/parental#3]
Hi,

Thanks for this package. I noticed that the $user record I got back doesn't have created_at, updated_at or any other datetime fields. But I'm not sure how to fix it. Hence raising an issue

Date fields only show up if I add them to the fillable array

& there are issues logging in when I have the ReturnsChildModels trait on my User model as well. Kept redirect back to login page. This happens even when type is null

In tests, $request->user() & auth()->user() seem to always return User too rather than their respective sub Models

**Comment by ziming** [comment]
Date fields only show up if I add them to the fillable array

**Comment by dallincoons** [comment]
The Id field is missing as well

**Comment by calebporzio** [comment]
#4 should have fixed this 👌 

Pull down v0.3-alpha for the fix
