### ISSUE TITLE
Polymorphic Relationship: Parent Morph Name

### ISSUE THREAD

**Issue by poing** [tightenco/parental#32]
*Forgive me, if it seems like I am rambling.  Trying to show what I want to accomplish.*

It looks like `parental` *almost* does what I am looking for.  The [Extending Models in Eloquent](https://tighten.co/blog/extending-models-in-eloquent) blog post, *almost* explains what I want to do.  But it's falling a *bit* short.

This may be the use case that #10 is looking for.  Where the parent morph name should be used by the extended model.  Or maybe I'm *just* missing something and need a better example.

I am trying to add a polymorphic relationship to an existing model from a package.  To make the package work, *without* requiring the developer to manually add the relationship to an existing class.

```php 
class User extends Model {
    // dev has to add this to the existing model
    public function posts() {
          return $this->morphMany(Vendor\Package\Post::class);
    }
}
$user = User::first();
$user->posts()->get();  // How it normally works.
```
----

Hoping I could leave `App\User` *untouched*, I tried the following:
```php 
class User extends Model {
    //
}

class UserPostRelationship extends User {
    public function posts() {
          return $this->morphMany(Vendor\Package\Post::class);
    }
}

$user = User::first();
$user->posts()->get();  // Call to undefined method App/User::posts()
```

This is where I stumbled across [Extending Models in Eloquent](https://tighten.co/blog/extending-models-in-eloquent).

*Maybe there's a way to push the function to `App\User` using `boot()`, but I am not sure if it's possible.* 

----

You've done a great job with `STI`, but it breaks existing polymorphic relationships that *may* already be in the `parent`.

```php 
class User extends Model {
    public function related() {
          return $this->morphMany(Related::class);
    }
}

class UserPostRelationship extends User {

    use Tightenco\Parental\HasParentModel;

    public function posts() {
          return $this->morphMany(Vendor\Package\Post::class);
    }
}

$user = UserPostRelationship::first();  // emulates App\User
$user->posts()->get();  // Works as expected
$user->related()->get();  // Is empty, since it's morph name is App\UserPostRelationship
```

----

`HasParentModel` is not as *clean* as I hoped.  But that **does not mean** I can't work with it.  Hopefully this helps other looking for a similar solution.

```txt
=> Illuminate\Database\Eloquent\Collection {#2963
     all: [
       App\Post {#2953
         id: 2662,
         content: null,
         user_id: 1,
         user_type: "App\UserPostRelationship",
         created_at: "2019-01-22 04:58:47",
         updated_at: "2019-01-22 04:58:47",
       },
     ],
   }
```

----

#### Use Case:

Here's my use case.  I have two separate packages with **polymorphic relationships** that I would like to tie together with App\User.
* `Vendor\Package\Post::class`
* `Vendor\Package\Star::class` *requires* `Vendor\Package\Post::class`

**and**

`App\User` has an **existing** polymorphic relationship I would like to use.

```php
$user = UserStarRelationship::first();  // Get a user
$user->stars()->get(); // Get relationships - this model only
$user->posts()->get(); // Can't see Post relationships
$user->related()->get();  // Can't see user relationships
$foo = UserPostRelationship::find($user->id); // Extra work required
$foo->posts()->get(); // But disconnected from User & Stars
$bar = User::find($user->id); // More work required
$bar->related()->get(); //  Disconnected from Posts & Stars
```

Maybe this is the only way it will work.  But fixing the morph name **could** help packages tie to existing model relationships.  *If the base model can not be directly extended.*

----

It also *seems* this is **not** possible.  But *again* is **could** be helpful for package development and distribution.  

```php
class UserPostRelationship extends User {
    use Tightenco\Parental\HasParentModel;
}

class UserStarRelationship extends UserPostRelationship {
    use Tightenco\Parental\HasParentModel;
}

$user = UserStarRelationship::first() // Table 'user_post_relationship' doesn't exist
```

**Comment by calebporzio** [comment]
Does the newly tagged version v0.6 satisfy this issue? There has been a fix for polymorphic relationships added. Let me know!

**Comment by pilishen** [comment]
version v0.6 doesn't seem to satisfy this issue
