### ISSUE TITLE
Can't associate records using save

### ISSUE THREAD

**Issue by JacobBennett** [tightenco/parental#5]
If I want to do something like this 

```
return $this->tracks()->save(new MyTrack());
```

where the parent is trying to create a related track item, it will fail because using `new` to create an instance of `MyTrack` will not fill in the `type` attribute. This currently works with `create` as follows.

```
return MyTrack::create(['refund_id' => $this->id]);
```

as the `newInstance` method is getting overridden. The suggestion then would be to eliminate the `newInstance` method, and instead move its logic into the `bootHasParentModel` inside a `static::saving(function ($model) {})` so that we could handle this for both the static `create` as well as the `hasMany->save()` situation.

**Comment by calebporzio** [comment]
Hey Jake, I moved the logic into `static::creating` thinking that should fix it - thoughts?

**Comment by calebporzio** [comment]
Alright, I added a test and it's working. Closing this for now. Keep me posted on the problem if it still persists @JacobBennett - thanks!

**Comment by JacobBennett** [comment]
Hey @calebporzio sorry for the late reply on this, I'll update and be sure all is well. Like I said, I couldn't get a failing test when I tried to write the implementation that was failing locally for me so likely was a problem in MY codebase. Thanks for your work on this.
