### ISSUE TITLE
Add child global scopes when querying parent

### ISSUE THREAD

**Issue by dallincoons** [tightenco/parental#6]
It would be nice if when querying for `Vehicle::all()` and Car extends Vehicle, for example, the global scope for Car would apply when returning instances of Car, but wouldn't apply to instances of Plane. Thoughts?

**Comment by calebporzio** [comment]
Sorry, mind clarify or re-stating the question?

**Comment by dallincoons** [comment]
Say you have a Car which extends Vehicle (which also has the ReturnsChildModel trait). Car has a global scope. When you query for Vehicle, you will potentially get instances of Car, however the global scope which applies to Car will now be used in this query. I think it would be great if global scopes of children applied automatically when querying against the parent.

I played around with a solution, and I don't see a great way of implementing this because parents don't have a way of knowing about children global scopes.

**Comment by calebporzio** [comment]
got it, thanks for clarifying

**Comment by calebporzio** [comment]
Yeah, this is a tough one, if it becomes an issue, let's reopen this and pursue a solution - but nothing jumps out at me right now.
